name: pusher_websocket
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  quiver: any
  synchronized: any
  logging: any
  web_socket_channel: ^1.1.0
  retry: ^3.0.1
  http: any
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
